version: '3'

services:
  amld_production:
    image: gcr.io/powerwork/powerwork-mpa-oil:ba4158701a39418e9588edb1c2ca80cb5dc7c4d1
    container_name: menfin_production
    environment:
      - VIRTUAL_HOST=richboxclub.com,www.richboxclub.com
      - LETSENCRYPT_HOST=richboxclub.com,www.richboxclub.com
      - LETSENCRYPT_EMAIL=powerwork.betoil@gmail.com
    volumes:
       - /var/app/config:/config:ro
    restart: always

