domain: "localhost:8080"
base_url: "http://localhost:8080"
shortener_url: "https://go.menfin.com"
db: "postgres://poweroil:WoRk1717@167.99.72.73/poweroildb?sslmode=require"
session_host: "localhost:6379"
session_prefix: "amld-stage:"
session_key: "aMLD213ddrewlsd:]{}lf@gSasdgapsz"
facebook_appid: "414711119471060"
facebook_secret: "8b31f65212db839115cf9a878bea1266"
google_cookie_secret: ""
bucket_name: "daml-bucket"
bucket_name_secret: "daml-bucket-secret"
datastorne_name: "powerworkamld"
service_account: "key.json"
webhook: "https://discordapp.com/api/webhooks/716948163856171009/DcIfZd8vEZniU8mplVHMlexnVfT-dcCgSMMShhflWPdVd3LgFCxgj_beiJD60jdZQOO4"
webhook_withdraw: "https://discordapp.com/api/webhooks/716948282215235644/kkR7D3cbQTQmFoiLlWKP5t4JRBOLoRERqZK2Kv3EQVVML5BzduVY6uZy6V-Y_2GgXfm1"
webhook_wallet: "https://discordapp.com/api/webhooks/716959248948396056/e5QTxS5_8lsXvrQU1I6g_l8y-R3MdLv73S5Qd__YZH-HA46DOjsSsH6fCKGf4o_bkaZ4"