routes:
  # general
  index: /
  privacy: /privacy
  register: /register
  condition: /condition
  contact: /contact
  wallet: /wallet
  notfound: /404
  help.post: /help/post
  test: /test

  # signin
  signin: /signin
  signin.email: /signin/email
  signin.facebook: /signin/facebook
  signin.facebook.callback: /signin/facebook/callback
  signin.google: /signin/google
  signin.google.callback: /signin/google/callback
  verify.email.callback: /verify/email/callback
  signout: /signout
  signup: /signup
  forgot: /forgot
  resetpassword: /resetpassword

  # app
  discover: /discover
  front.back: /game/headtails
  follow: /follow
  liked: /liked
  category.get: /category/
  addcoin: /addcoin
  withdraw.money: /withdraw/money

  # public: /public
  create.post: /create/post
  create.post.undraft: /create/post/undraft
  create.gap: /create/gap
  edit.post: /edit/post/
  delete.post: /delete/post/
  profile: /profile
  category: /category
  topic: /topic/
  topic.select: /topic/select
  post.read: /post/

  # gap
  gap: /gap/
  gap.setting.info: /gap/setting/info
  gap.setting.username: /gap/setting/username
  gap.setting.contact: /gap/setting/contact
  gap.setting.address: /gap/setting/address

  account: /account
  notification: /notification
  search: /search

  # ajax
  ajax.gap.follow: /ajax/follow/gap
  ajax.gap.list.user.follower: /ajax/list/user/follower/gap
  ajax.profile.upload.display: /ajax/upload/display/profile
  ajax.profile.verify.creator: /ajax/verify/creator/profile
  ajax.profile.verify.email: /ajax/verify/email/profile
  ajax.profile.verify.bookbank: /ajax/verify/bookbank/profile
  ajax.gap.upload.display: /ajax/upload/display/gap/
  ajax.gap.upload.cover: /ajax/upload/cover/gap/
  ajax.topic.follow: /ajax/follow/topic
  ajax.search.tagtopic: /ajax/search/tagtopic
  ajax.search.navigationbar: /ajax/search/navigationbar
  ajax.post.like: /ajax/like
  ajax.post.image: /ajax/post/image
  ajax.post.draft.article: /ajax/post/draft/article
  ajax.post.discover: /ajax/post/discover
  ajax.post.follow: /ajax/post/follow
  ajax.post.public: /ajax/post/public
  ajax.post.liked: /ajax/post/like
  ajax.post.read: /ajax/post/read/
  ajax.post.category: /ajax/post/category/
  ajax.post.topic: /ajax/post/topic/
  ajax.post.gap: /ajax/post/gap/
  ajax.post.shortener.url: /ajax/post/shortener/url
  ajax.user.list.gap.follow: /ajax/list/user/follow/gap
  ajax.comment.list: /ajax/comment/list
  ajax.comment.post: /ajax/comment/post
  ajax.comment.delete: /ajax/comment/delete
  ajax.comment.edit: /ajax/comment/edit
  ajax.notification.list: /ajax/notification/list
  ajax.notification.list.type: /ajax/notification/list/type
  ajax.notification.read: /ajax/notification/read
  ajax.notification.read.all: /ajax/notification/read/all
  ajax.notification.reset: /ajax/notification/reset
  ajax.gap.statistic.post: /ajax/gap/statistic/post
  ajax.gap.revenue.post: /ajax/gap/revenue/post
  ajax.gap.revenue.register: /ajax/gap/revenue/register
  ajax.topic.list: /ajax/topic/list
  ajax.frontback.bet: /ajax/frontback/bet
  ajax.highlow.bet: /ajax/highlow/bet
  ajax.highlow.withdraw: /ajax/highlow/withdraw

  # admin
  admin: /admin
  admin.user: /admin/user
  admin.verify: /admin/verify
  admin.verify.detail: /admin/verify/detail
  admin.verify.idcard: /admin/idcard/verify
  admin.verify.bookbank: /admin/bookbank/verify
  admin.revenue: /admin/revenue
  admin.revenue.history: /admin/revenue/history
  admin.revenue.detail: /admin/revenue/detail
  admin.gap.recommend: /admin/gap/recommend
  admin.gap.recommend.register: /admin/gap/recommend/register
  admin.gap.recommend.delete: /admin/gap/recommend/delete
  admin.category: /admin/category
  admin.category.create: /admin/category/create
  admin.category.edit: /admin/category/edit
  admin.topic: /admin/topic
  admin.topic.create: /admin/topic/create
  admin.topic.edit: /admin/topic/edit
  admin.topic.seo: /admin/topic/seo
  admin.topic.seo.edit: /admin/topic/seo/edit
  admin.addcoin: /admin/addcoin
  admin.addcoin.route: /addcoin
  admin.withdraw.money: /admin/withdraw/money
  admin.selectuser: /admin/selectuser


  admin.ajax.revenue.post: /admin/ajax/revenue/post
  admin.ajax.revenue.approve: /admin/ajax/revenue/approve
  admin.ajax.revenue.reject: /admin/ajax/revenue/reject
  admin.ajax.post.reject: /admin/ajax/post/reject
  admin.ajax.post.delete: /admin/ajax/post/delete
